version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        environment:
            - cluster.name=docker-elk-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.3
        environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:6.5.3
        ports:
            - 5044:5044
        volumes:
            - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
        command: bash -c "logstash -f /usr/share/logstash/config/logstash.conf"
        depends_on:
            - elasticsearch
